name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore API
        run: dotnet restore SmartCities.Api

      - name: Run API (background)
        run: |
          cd SmartCities.Api
          dotnet run &

      - name: Restore tests
        run: dotnet restore SmartCities-Tests/tests/SmartCities.Tests

      - name: Execute tests
        run: dotnet test SmartCities-Tests/tests/SmartCities.Tests --no-build --logger trx

      - name: Publish LivingDoc
        run: |
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
          livingdoc test-assembly             --project tests/SmartCities.Tests             --output Report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: TestsReport
          path: Report.html
